---
apiVersion: v1
kind: Pod
metadata:
  name: sleeper-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: sleeper
      image: "library/busybox"
      command: ["/bin/bash", "-c", 'sleep 100']
  nodeSelector:
    node.kubernetes.io/instance-type: mac1.metal

