apiVersion: v1
kind: Pod
metadata:
  name: log-test-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: sleeper
      image: "library/busybox"
      command: ["/bin/bash", "-c", 'yes | head -n5' , '&&', 'sleep 3600']
