name: CRI validation  tests

on:
  push:
    paths:
      - 'procri/**'

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  cri-tests:
    name: Tests
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Install critest tool
        env:
          VERSION: v1.20.0
        run: |
          wget https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/critest-$VERSION-darwin-amd64.tar.gz
          sudo tar zxvf critest-$VERSION-darwin-amd64.tar.gz -C /usr/local/bin
          critest -version
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Runs the Super-Linter action
      - name: Run CRI-tests
        run: |
          ./procri/scripts/run_cri_validation_tests.sh
