on:
  push:
    paths-ignore:
      - 'deploy/**'
      - 'docs/**'
name: E2E kubelet tests (v1.19)
jobs:
  test:
    if: "contains(github.event.head_commit.message, '[e2e-test]')"
    runs-on: macos-10.15
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - run: git fetch origin +refs/tags/*:refs/tags/*
      - uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('procri/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test kubelet v1.19.13
        run: |
          cd system_test/
          ./run_kubelet_test.sh
        env:
          KUBELET_BIN_URL: "https://elotl-maccri.s3.amazonaws.com/kubelet-v1.19.8-rc.0-344-g9e6d8223595"
          K8S_BIN_URL: "https://elotl-maccri.s3.amazonaws.com/kubernetes-v1.19.13etcd-v3.4.13-bin-darwin-amd64.tar.gz"
